### ISSUE TITLE
Error in AndroidManifest.xml: Tag <provider> attribute authorities has invalid character '{'

### ISSUE THREAD

**Issue by pcmueller77** [JimmyPun610/Plugin.XF.AppInstallHelper#1]
Hello, first thanks for the great idea, and now I'm not able to get my test-project running.
I use VS2017, And the dependencies I attached as an image. Can you provide help, or a sample project, so I can compare? Thank's a lot!
With best regards, Thomas.
![2019-04-17 23_30_42-Window](https://user-images.githubusercontent.com/20625140/56322277-e3ed8d00-6168-11e9-8091-98ddbfbc0df5.png)

**Comment by JimmyPun610** [comment]
Hi Thomas,

In your case, you may use "com.companyname.Update_Test.Android" to replace {packagename} in manifest.xml
In MainActivity.cs, please use
Plugin.XF.AppInstallHelper.CrossInstallHelper.Current.Init("com.companyname.Update_Test.Android.fileprovider");

Example 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="6" android:versionName="1.5" package="mypackage" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="19" />
	<application android:label="測試-石矢入閘" android:resizeableActivity="false">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="mypackage.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
		</provider>
	</application>
<!--User permission part -->
</manifest>

```c#
Plugin.XF.AppInstallHelper.CrossInstallHelper.Current.Init("mypackage.fileprovider");

```


Please let me know if it is ok or not. Thank you
