### ISSUE TITLE
Java.Lang.NullPointerException on Android 10 device

### ISSUE THREAD

**Issue by SunshineSpring666** [JimmyPun610/Plugin.XF.AppInstallHelper#3]
Hi Jimmy~ Excellent work, we all appreciated that! Here we encountered a little problem:

When attempting to install on Android 10 devices, 
**An error showed up:**
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference'

**The code is as follows:**
string apkPath = "file:///storage/emulated/0/Download/AppName.1.0-8.apk";
await Plugin.XF.AppInstallHelper.CrossInstallHelper.Current.InstallApp(apkPath, Plugin.XF.AppInstallHelper.Abstractions.InstallMode.OutOfAppStore);

Anything we are doing wrong? Please help. Thanks~

**Comment by JimmyPun610** [comment]
I guess the configuration is not complete
for manifest.xml, you should replace {packagename} to your app id
```xml
  <provider android:name="android.support.v4.content.FileProvider" android:authorities="{packagename}.fileprovider" android:exported="false" android:grantUriPermissions="true">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
    </provider>
```
In MainActivity.cs
You should add
```C#
Plugin.XF.AppInstallHelper.CrossInstallHelper.Current.Init("{packagename}.fileprovider");
```
Also, replace {packagename} to your app id

**Comment by SunshineSpring666** [comment]
Thanks. Installation fails on a Mate 30 pro (Android 10) with the following error message:
**"Package signature does not match the installed app".**
Even though I
1) deleted and reinstall the app, or 
2) set the update package exactly the same as the installed one
**both packages are archived(release mode) and distributed(ad-hoc) using the same signing identity.**
I researched other threads and tried, but no proper solution found.
Any way to solve this issue?  Many thanks!

**Comment by SunshineSpring666** [comment]
BTW, you may add UWP sideload support

for anyone with a solution targeting all three major platforms, the nuget package could not be in installed in shared project (for it will cause exception in UWP at runtime).

So, currently I encapsulate your library in another dependency service to support UWP update sideload.  Code snippet:

public async Task<bool> Install(string stringUri)
        {
            try
            {
                return await Windows.System.Launcher.LaunchUriAsync(new Uri("ms-appinstaller:?source=" + stringUri));
            }
            catch (Exception ex)
            {
                return false;
            }
        }

**Comment by JimmyPun610** [comment]
I think this issue is out of the library.
You may try to do the update procedure manually. 
I.E. install version 1 first, then use explorer to install version 2.
The result will be the same.

You may check
1. Version number of both apk. 
2. Remove original app => Restart => install version 1 => install version 2
3. Use another android which did not install the app in debug mode before to test the problem exist or not

**Comment by SunshineSpring666** [comment]
Thanks. **Please add UWP support, because for the moment, if the Solution contains a UWP project, the user have to put this library in platform specific code using DependencyService. If not, the NuGet package of this library will lead to runtime exception.**

-  **Code Snippet for UWP sideload is as follow:**

public async Task<bool> Install(string stringUri)
        {
            try
            {
                return await Windows.System.Launcher.LaunchUriAsync(new Uri("ms-appinstaller:?source=" + stringUri));
            }
            catch (Exception ex)
            {
                return false;
            }
        }
This code works ok.


-  **For UWP MicrosoftStore update, please refer to :**
https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates

**Comment by JimmyPun610** [comment]
I am not familiar with UWP. 
Could you enhance and create a pull request on that?

**Comment by SunshineSpring666** [comment]
I'll try it after work to see if I can handle that~ Thanks again for this awesome lib.
