### ISSUE TITLE
Compatible with MAUI, the next version of Xamarin

### ISSUE THREAD

**Issue by SunshineSpring666** [JimmyPun610/Plugin.XF.AppInstallHelper#7]
Hi Jimmy,
    The AppInstallHelper is great. It simplifies the code of updating app packages. Thanks a lot.
    Are there any plan of releasing a version which works with MAUI preview (the enhancement version of Xamarin)?

    Best Regards,
    Sunshine

**Comment by JimmyPun610** [comment]
Hi @SunshineSpring666 ,

I didn't try MAUI yet. But I think it is more about the frontend part and may not affect the usage of this library?
Or do you get any error when apply this library to MAUI?

**Comment by SunshineSpring666** [comment]
Hi Jimmy,
    The compatibility is not known yet. I didn't manage to set up a MAUI environment with current VS preview, maybe due to some dependency issues. I'll give you feedback once the demo is executable.
    Thanks a lot.

**Comment by SunshineSpring666** [comment]
Hi Jimmy,
    This library does not seem to be compatible with MAUI. When installing this library in a MAUI project, I get issue related to dependency/conflict issue, here is the detail:

NU1107: Version conflict detected for Xamarin.AndroidX.Browser. Install/reference Xamarin.AndroidX.Browser 1.4.0.1 directly to project MauiApp1 to resolve this issue. 
 MauiApp1 -> Microsoft.Maui.Dependencies 6.0.400 -> Xamarin.AndroidX.Browser (>= 1.4.0.1) 
 MauiApp1 -> Plugin.XF.AppInstallHelper 2.1.0 -> Xamarin.Essentials 1.7.1 -> Xamarin.AndroidX.Browser (>= 1.3.0.5 && < 1.4.0).

Could you please release a MAUI version of this library? Thanks.
Best Regards

**Comment by JimmyPun610** [comment]
Just made a pre-release for MAUI...I just tested with Android but not iOS.
Please take a look in Readme.md for more information...(installation etc...)

**Comment by SunshineSpring666** [comment]
Thanks a lot, Jimmy.
