### ISSUE TITLE
ERROR when Using API 30

### ISSUE THREAD

**Issue by Theysoft** [JimmyPun610/Plugin.XF.AppInstallHelper#8]
hello there some restriction in using Externale storage starting from Andriod 11 , can you please find a solution for this problmme thanks

**Comment by JimmyPun610** [comment]
How error exactly?
Just tested with my Pixel 3 and looks good.
The project should be targeting SDK 30 for a while.

**Comment by JimmyPun610** [comment]
Just added some checking in latest android version....
